INSERT OR IGNORE INTO checklist_doc_types (stage, discipline, item_code, item_name, doc_name, sort_order) VALUES
('TKCS','HTKT','CL',NULL,'San nền',1),
('TKCS','HTKT','CT',NULL,'Giao thông (Cầu, đường)',2),
('TKCS','HTKT','CD',NULL,'Thoát nước mưa',3),
('TKCS','HTKT','CS',NULL,'Thoát nước thải',4),
('TKCS','HTKT','CW',NULL,'Cấp nước sinh hoạt',5),
('TKCS','HTKT','CF',NULL,'Cấp nước chữa cháy',6),
('TKCS','HTKT','CE',NULL,'Cấp điện',7),
('TKCS','HTKT','CC',NULL,'Thông tin liên lạc',8),
('TKCS','KIẾN TRÚC',NULL,NULL,'Thuyết Minh',9),
('TKCS','KIẾN TRÚC','A1',NULL,'Nhà A',10),
('TKCS','KIẾN TRÚC',NULL,NULL,'Tổng Mặt Bằng',11),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Định Vị',12),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Kiến Trúc',13),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Đứng',14),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Cắt',15),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Kiến Trúc PCCC',16),
('TKCS','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang PCCC',17),
('TKCS','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang Máy PCCC',18),
('TKCS','KIẾN TRÚC',NULL,NULL,'Chi Tiết Cửa PCCC',19),
('TKCS','KIẾN TRÚC','A2',NULL,'Nhà B',20),
('TKCS','KIẾN TRÚC',NULL,NULL,'Tổng Mặt Bằng',21),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Định Vị',22),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Kiến Trúc',23),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Đứng',24),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Cắt',25),
('TKCS','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Kiến Trúc PCCC',26),
('TKCS','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang PCCC',27),
('TKCS','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang Máy PCCC',28),
('TKCS','KIẾN TRÚC',NULL,NULL,'Chi Tiết Cửa PCCC',29),
('TKCS','KẾT CẤU',NULL,NULL,'Thuyết Minh',30),
('TKCS','KẾT CẤU','A1',NULL,'Nhà A',31),
('TKCS','KẾT CẤU',NULL,NULL,'Mặt Bằng Móng',32),
('TKCS','KẾT CẤU',NULL,NULL,'Mặt Bằng Định Vị Cột',33),
('TKCS','KẾT CẤU',NULL,NULL,'Mặt Bằng Dầm Sàn',34),
('TKCS','KẾT CẤU',NULL,NULL,'Chi Tiết',35),
('TKCS','KẾT CẤU','A2',NULL,'Nhà B',36),
('TKCS','KẾT CẤU',NULL,NULL,'Mặt Bằng Móng',37),
('TKCS','KẾT CẤU',NULL,NULL,'Mặt Bằng Định Vị Cột',38),
('TKCS','KẾT CẤU',NULL,NULL,'Mặt Bằng Dầm Sàn',39),
('TKCS','KẾT CẤU',NULL,NULL,'Chi Tiết',40),
('TKCS','CƠ ĐIỆN',NULL,NULL,'Thuyết Minh',41),
('TKCS','PCCC','A1',NULL,'Nhà A',42),
('TKCS','PCCC',NULL,NULL,'Sơ đồ nguyên lý',43),
('TKCS','PCCC',NULL,NULL,'Mặt Bằng',44),
('TKCS','PCCC',NULL,NULL,'Chi tiết/Ghi chú chung',45),
('TKCS','PCCC','A2',NULL,'Nhà B',46),
('TKCS','PCCC',NULL,NULL,'Sơ đồ nguyên lý',47),
('TKCS','PCCC',NULL,NULL,'Mặt Bằng',48),
('TKCS','PCCC',NULL,NULL,'Chi tiết/Ghi chú chung',49),
('TKCS','HVAC','A1',NULL,'Nhà A',50),
('TKCS','HVAC',NULL,NULL,'Sơ đồ nguyên lý',51),
('TKCS','HVAC',NULL,NULL,'Mặt Bằng',52),
('TKCS','HVAC',NULL,NULL,'Chi tiết/Ghi chú chung',53),
('TKCS','HVAC','A2',NULL,'Nhà B',54),
('TKCS','HVAC',NULL,NULL,'Sơ đồ nguyên lý',55),
('TKCS','HVAC',NULL,NULL,'Mặt Bằng',56),
('TKCS','HVAC',NULL,NULL,'Chi tiết/Ghi chú chung',57),
('TKCS','ĐIỆN NẶNG','A1',NULL,'Nhà A',58),
('TKCS','ĐIỆN NẶNG',NULL,NULL,'Sơ đồ nguyên lý',59),
('TKCS','ĐIỆN NẶNG',NULL,NULL,'Mặt Bằng',60),
('TKCS','ĐIỆN NẶNG',NULL,NULL,'Chi tiết/Ghi chú chung',61),
('TKCS','ĐIỆN NẶNG','A2',NULL,'Nhà B',62),
('TKCS','ĐIỆN NẶNG',NULL,NULL,'Sơ đồ nguyên lý',63),
('TKCS','ĐIỆN NẶNG',NULL,NULL,'Mặt Bằng',64),
('TKCS','ĐIỆN NẶNG',NULL,NULL,'Chi tiết/Ghi chú chung',65),
('TKCS','ĐIỆN NHẸ','A1',NULL,'Nhà A',66),
('TKCS','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý',67),
('TKCS','ĐIỆN NHẸ',NULL,NULL,'Mặt Bằng',68),
('TKCS','ĐIỆN NHẸ',NULL,NULL,'Chi tiết/Ghi chú chung',69),
('TKCS','ĐIỆN NHẸ','A2',NULL,'Nhà B',70),
('TKCS','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý',71),
('TKCS','ĐIỆN NHẸ',NULL,NULL,'Mặt Bằng',72),
('TKCS','ĐIỆN NHẸ',NULL,NULL,'Chi tiết/Ghi chú chung',73),
('TKCS','CẤP THOÁT NƯỚC','A1',NULL,'Nhà A',74),
('TKCS','CẤP THOÁT NƯỚC',NULL,NULL,'Sơ đồ nguyên lý',75),
('TKCS','CẤP THOÁT NƯỚC',NULL,NULL,'Mặt Bằng',76),
('TKCS','CẤP THOÁT NƯỚC',NULL,NULL,'Chi tiết/Ghi chú chung',77),
('TKCS','CẤP THOÁT NƯỚC','A2',NULL,'Nhà B',78),
('TKCS','CẤP THOÁT NƯỚC',NULL,NULL,'Sơ đồ nguyên lý',79),
('TKCS','CẤP THOÁT NƯỚC',NULL,NULL,'Mặt Bằng',80),
('TKCS','CẤP THOÁT NƯỚC',NULL,NULL,'Chi tiết/Ghi chú chung',81),
('BVTC','HTKT','CL',NULL,'San nền',1),
('BVTC','HTKT','CT',NULL,'Giao thông (Cầu, đường)',2),
('BVTC','HTKT','CD',NULL,'Thoát nước mưa',3),
('BVTC','HTKT','CS',NULL,'Thoát nước thải',4),
('BVTC','HTKT','CW',NULL,'Cấp nước sinh hoạt',5),
('BVTC','HTKT','CF',NULL,'Cấp nước chữa cháy',6),
('BVTC','HTKT','CE',NULL,'Cấp điện',7),
('BVTC','HTKT','CC',NULL,'Thông tin liên lạc',8),
('BVTC','KIẾN TRÚC',NULL,NULL,'Thuyết Minh',9),
('BVTC','KIẾN TRÚC','A1',NULL,'Nhà A',10),
('BVTC','KIẾN TRÚC',NULL,NULL,'Ghi Chú Chung',11),
('BVTC','KIẾN TRÚC',NULL,NULL,'Bảng tổng hợp Vật liệu hoàn thiện',12),
('BVTC','KIẾN TRÚC',NULL,NULL,'Tổng Mặt Bằng',13),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Định Vị',14),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Kiến Trúc',15),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Tường xây-Kích Thước',16),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt BằngLát Sàn',17),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Trần',18),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Chống thấm',19),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Định Vị cửa & Vách Kính',20),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Đứng',21),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Mặt Đứng',22),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Cắt',23),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Mặt Cắt',24),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang',25),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang Máy',26),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Cửa Đi, Cửa Sổ & Vách kính',27),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết WC',28),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết khác',29),
('BVTC','KIẾN TRÚC','A2',NULL,'Nhà B',30),
('BVTC','KIẾN TRÚC',NULL,NULL,'Ghi Chú Chung',31),
('BVTC','KIẾN TRÚC',NULL,NULL,'Bảng tổng hợp Vật liệu hoàn thiện',32),
('BVTC','KIẾN TRÚC',NULL,NULL,'Tổng Mặt Bằng',33),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Định Vị',34),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Kiến Trúc',35),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Tường xây-Kích Thước',36),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt BằngLát Sàn',37),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Trần',38),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Chống thấm',39),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Định Vị cửa & Vách Kính',40),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Đứng',41),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Mặt Đứng',42),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Cắt',43),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Mặt Cắt',44),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang',45),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Thang Máy',46),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết Cửa Đi, Cửa Sổ & Vách kính',47),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết WC',48),
('BVTC','KIẾN TRÚC',NULL,NULL,'Chi Tiết khác',49),
('BVTC','KIẾN TRÚC',NULL,NULL,'Mặt Bằng Parking & Chi tiết (nếu có)',50),
('BVTC','KẾT CẤU',NULL,NULL,'Thuyết Minh',51),
('BVTC','KẾT CẤU','A1',NULL,'Nhà A',52),
('BVTC','KẾT CẤU',NULL,NULL,'Ghi Chú Chung',53),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt Bằng Định vị cọc/hố Móng',54),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt Bằng Móng và Dầm Móng',55),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Móng & Dầm Móng',56),
('BVTC','KẾT CẤU',NULL,NULL,'Chi tiết các bể nước ngầm, bể phốt (nếu có)',57),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt Bằng Định Vị Cột, vách',58),
('BVTC','KẾT CẤU',NULL,NULL,'Chi tiết Cột, vách',59),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt bằng Kết Cấu các Tầng',60),
('BVTC','KẾT CẤU',NULL,NULL,'Chi tiết cốt thép Dầm',61),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Cốt Thép Sàn',62),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Kết Cấu Cầu Thang',63),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Kết Cấu Lanh Tô, Ô Văng, Mái dốc',64),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Kết Cấu Mái',65),
('BVTC','KẾT CẤU',NULL,NULL,'Bảng Thống Kê Chi Tiết',66),
('BVTC','KẾT CẤU','A2',NULL,'Nhà B',67),
('BVTC','KẾT CẤU',NULL,NULL,'Ghi Chú Chung',68),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt Bằng Định vị cọc/hố Móng',69),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt Bằng Móng và Dầm Móng',70),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Móng & Dầm Móng',71),
('BVTC','KẾT CẤU',NULL,NULL,'Chi tiết các bể nước ngầm, bể phốt (nếu có)',72),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt Bằng Định Vị Cột, vách',73),
('BVTC','KẾT CẤU',NULL,NULL,'Chi tiết Cột, vách',74),
('BVTC','KẾT CẤU',NULL,NULL,'Mặt bằng Kết Cấu các Tầng',75),
('BVTC','KẾT CẤU',NULL,NULL,'Chi tiết cốt thép Dầm',76),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Cốt Thép Sàn',77),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Kết Cấu Cầu Thang',78),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Kết Cấu Lanh Tô, Ô Văng, Mái dốc',79),
('BVTC','KẾT CẤU',NULL,NULL,'Chi Tiết Kết Cấu Mái',80),
('BVTC','KẾT CẤU',NULL,NULL,'Bảng Thống Kê Chi Tiết',81),
('BVTC','CƠ ĐIỆN',NULL,NULL,'Thuyết Minh',82),
('BVTC','PCCC','A1',NULL,'Nhà A',83),
('BVTC','PCCC',NULL,NULL,'Ghi Chú Chung',84),
('BVTC','PCCC',NULL,NULL,'Sơ đồ nguyên lý Chữa cháy',85),
('BVTC','PCCC',NULL,NULL,'Mặt Bằng Trạm bơm và bể PCCC',86),
('BVTC','PCCC',NULL,NULL,'Mặt bằng hệ thống Sprikler',87),
('BVTC','PCCC',NULL,NULL,'Mặt bằng /Sơ đồ hệ thống đặc biệt (nếu có)',88),
('BVTC','PCCC',NULL,NULL,'Chi tiết lắp đặt',89),
('BVTC','PCCC',NULL,NULL,'Sơ đồ nguyên lý hệ thống báo cháy',90),
('BVTC','PCCC',NULL,NULL,'Mặt bằng bố trí báo cháy các tầng',91),
('BVTC','PCCC',NULL,NULL,'Mặt bằng đi dây & ống luồn dây',92),
('BVTC','PCCC',NULL,NULL,'Sơ đồ điều khiển liên động',93),
('BVTC','PCCC',NULL,NULL,'Mặt bằng bố trí đèn sự cố',94),
('BVTC','PCCC','A2',NULL,'Nhà B',95),
('BVTC','PCCC',NULL,NULL,'Ghi Chú Chung',96),
('BVTC','PCCC',NULL,NULL,'Sơ đồ nguyên lý Chữa cháy',97),
('BVTC','PCCC',NULL,NULL,'Mặt Bằng Trạm bơm và bể PCCC',98),
('BVTC','PCCC',NULL,NULL,'Mặt bằng hệ thống Sprikler',99),
('BVTC','PCCC',NULL,NULL,'Mặt bằng /Sơ đồ hệ thống đặc biệt (nếu có)',100),
('BVTC','PCCC',NULL,NULL,'Chi tiết lắp đặt',101),
('BVTC','PCCC',NULL,NULL,'Sơ đồ nguyên lý hệ thống báo cháy',102),
('BVTC','PCCC',NULL,NULL,'Mặt bằng bố trí báo cháy các tầng',103),
('BVTC','PCCC',NULL,NULL,'Mặt bằng đi dây & ống luồn dây',104),
('BVTC','PCCC',NULL,NULL,'Sơ đồ điều khiển liên động',105),
('BVTC','PCCC',NULL,NULL,'Mặt bằng bố trí đèn sự cố',106),
('BVTC','HVAC','A1',NULL,'Nhà A',107),
('BVTC','HVAC',NULL,NULL,'Ghi Chú Chung',108),
('BVTC','HVAC',NULL,NULL,'Sơ đồ nguyên lý hệ thống điều hòa không khí',109),
('BVTC','HVAC',NULL,NULL,'Sơ đồ nguyên lý hệ thống thông gió và Kiểm soát sự cố',110),
('BVTC','HVAC',NULL,NULL,'Sơ đồ nguyên lý hệ thống Điều khiển và ga/ nước ngưng',111),
('BVTC','HVAC',NULL,NULL,'Mặt Bằng thiết bị HVAC',112),
('BVTC','HVAC',NULL,NULL,'Mặt bằng Thi Công hệ thống Ống gió',113),
('BVTC','HVAC',NULL,NULL,'Mặt bằng thi công đường ống ga & nước ngưng',114),
('BVTC','HVAC',NULL,NULL,'Chi tiết lắp đặt & mặt cắt',115),
('BVTC','HVAC','A2',NULL,'Nhà B',116),
('BVTC','HVAC',NULL,NULL,'Ghi Chú Chung',117),
('BVTC','HVAC',NULL,NULL,'Sơ đồ nguyên lý hệ thống điều hòa không khí',118),
('BVTC','HVAC',NULL,NULL,'Sơ đồ nguyên lý hệ thống thông gió và Kiểm soát sự cố',119),
('BVTC','HVAC',NULL,NULL,'Sơ đồ nguyên lý hệ thống Điều khiển và ga/ nước ngưng',120),
('BVTC','HVAC',NULL,NULL,'Mặt Bằng thiết bị HVAC',121),
('BVTC','HVAC',NULL,NULL,'Mặt bằng Thi Công hệ thống Ống gió',122),
('BVTC','HVAC',NULL,NULL,'Mặt bằng thi công đường ống ga & nước ngưng',123),
('BVTC','HVAC',NULL,NULL,'Chi tiết lắp đặt & mặt cắt',124),
('BVTC','ĐIỆN NẶNG','A1',NULL,'Nhà A',125),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Ghi Chú Chung',126),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Bảng tổng hợp phụ tải',127),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Sơ đồ nguyên lý Toàn tòa nhà & các Tầng',128),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Mặt Bằng công tắc chiếu sáng',129),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Mặt Bằng cấp nguồn & ổ cắm',130),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Hệ Thống Mang Cáp, Máng cáp',131),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Mặt bằng Trạm biến Áp, P.Tủ điện tổng',132),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Hệ Thống Chống sét &Tiếp Địa',133),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Chi tiết lắp đặt & mặt cắt',134),
('BVTC','ĐIỆN NẶNG','A2',NULL,'Nhà B',135),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Ghi Chú Chung',136),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Bảng tổng hợp phụ tải',137),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Sơ đồ nguyên lý Toàn tòa nhà & các Tầng',138),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Mặt Bằng công tắc chiếu sáng',139),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Mặt Bằng cấp nguồn & ổ cắm',140),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Hệ Thống Mang Cáp, Máng cáp',141),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Mặt bằng Trạm biến Áp, P.Tủ điện tổng',142),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Hệ Thống Chống sét &Tiếp Địa',143),
('BVTC','ĐIỆN NẶNG',NULL,NULL,'Chi tiết lắp đặt & mặt cắt',144),
('BVTC','ĐIỆN NHẸ','A1',NULL,'Nhà A',145),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Ghi Chú Chung',146),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý mạng Lan,Wifi & điện thoại',147),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý hệ thống Camera & giám sát',148),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý hệ thống Âm Thanh Công Cộng',149),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý kiểm soát vào ra & Chuông cửa có hình',150),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Mặt Bằng bố trí thiết bị',151),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Mặt Bằng Đi dây & luồn dây',152),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Chi tiết lắp đặt & chi tiết tủ Rack',153),
('BVTC','ĐIỆN NHẸ','A2',NULL,'Nhà B',154),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Ghi Chú Chung',155),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý mạng Lan,Wifi & điện thoại',156),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý hệ thống Camera & giám sát',157),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý hệ thống Âm Thanh Công Cộng',158),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Sơ đồ nguyên lý kiểm soát vào ra & Chuông cửa có hình',159),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Mặt Bằng bố trí thiết bị',160),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Mặt Bằng Đi dây & luồn dây',161),
('BVTC','ĐIỆN NHẸ',NULL,NULL,'Chi tiết lắp đặt & chi tiết tủ Rack',162),
('BVTC','CẤP THOÁT NƯỚC','A1',NULL,'Nhà A',163),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Ghi Chú Chung',164),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Sơ đồ nguyên lý cấp nước',165),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Sơ đồ nguyên lý Thoát nước & Thông Hơi',166),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Mặt Bằng cấp nước tổng thể',167),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Mặt Bằng cấp thoát nước các tầng',168),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Chi tiết cấp thoát nước vệ sinh',169),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Chi tiết lắp đặt & mặt cắt',170),
('BVTC','CẤP THOÁT NƯỚC','A2',NULL,'Nhà B',171),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Ghi Chú Chung',172),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Sơ đồ nguyên lý cấp nước',173),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Sơ đồ nguyên lý Thoát nước & Thông Hơi',174),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Mặt Bằng cấp nước tổng thể',175),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Mặt Bằng cấp thoát nước các tầng',176),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Chi tiết cấp thoát nước vệ sinh',177),
('BVTC','CẤP THOÁT NƯỚC',NULL,NULL,'Chi tiết lắp đặt & mặt cắt',178),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Ghi Chú Chung Hardscape',180),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Tổng Mặt Bằng Định Vị Phân vùng vật liệu',181),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt Bằng cao độ san nền',182),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt Cắt phần Hardscape',183),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Ghi Chú Chung Softscape',184),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt bằng bố trí cây xanh bóng mát câu bụi tầng cao',185),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt bằng bố trí cây bụi',186),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Bản vẽ chi tiết quy cách trồng cây',187),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt Bằng Hệ thống tưới nước',188),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt Bằng Hệ thống Thoát Nước',189),
('BVTC','CẢNH QUAN','LA','Cảnh quan','Mặt Bằng Chiếu sáng cảnh quan',190),
('BVTC','NỘI THẤT','ID','Nội thất','Ghi Chú Chung',192),
('BVTC','NỘI THẤT','ID','Nội thất','Bảng Tổng Hợp Vật Liệu',193),
('BVTC','NỘI THẤT','ID','Nội thất','Mặt Bằng Định Vị',194),
('BVTC','NỘI THẤT','ID','Nội thất','Mặt Bằng Bố trí vật dụng',195),
('BVTC','NỘI THẤT','ID','Nội thất','Mặt Bằng Trần đèn',196),
('BVTC','NỘI THẤT','ID','Nội thất','Mặt Đứng',197),
('BVTC','NỘI THẤT','ID','Nội thất','Mặt Cắt',198),
('BVTC','NỘI THẤT','ID','Nội thất','Chi Tiết vật dụng đồ rời….',199);